### ISSUE TITLE
Doubt about the usage of RpLidarScan object

### ISSUE THREAD

**Issue by jabrena** [soblenes32/AutonomousSnowplow#1]
Good morning @soblenes32,

This weekend, I was thinking about your performance comment and I checked your class: RPLidarService and I notice that you get a good performance with the sensor.

Checking the class, I have a doubt about this if:

``` java
//RpLidarScan.N: rplidar data is stored in a sparse array of 360 degrees * 64 degreefractions
for (int j = 0; j < RpLidarScan.N; j++) {
	Date scanTime = new Date(scan.time[j]);
	if( scan.distance[j] != 0 && scanTime.after(lastScanThreshold)) {
		//System.out.println(scan.distance[j]);
		System.out.println(scan.distance.length);
	}
}

``` 

why do you do this if:

``` java
		//System.out.println(scan.distance[j]);
		System.out.println(scan.distance.length);
	}
```

With your implementation I am receiving: 23039 per iteration, it is a fantastic number!

```
ev3dev#1|Initial scan request failed
ev3dev#1|23039
ev3dev#1|Counter: 1
ev3dev#1|23039
ev3dev#1|Counter: 2
ev3dev#1|23039
ev3dev#1|Counter: 3
ev3dev#1|23039
ev3dev#1|Counter: 4
ev3dev#1|23039
ev3dev#1|Counter: 5
ev3dev#1|Finishing stop command.
```

Many thanks in advance.

Juan Antonio

**Comment by soblenes32** [comment]
Hi @jabrena 
The purpose of the IF statement is to ensure that my program is not reading the same scan value multiple times per rotation, since unlike the reference implementation, my code is operating off of a strict 20hz thread scheduler instead of waiting for the lidar to complete a 360 degree scan. Without the IF condition, it will simply read the same values out of the circular queue (scan.distance) which provide no additional value. 

Empirically, my device seems to achieve scan rates of about 2k/s. According to the RPLidar A2 spec sheet and protocol, the device should be capable of scanning 4k/s, but only in [express scan mode](http://www.robotshop.com/media/files/pdf2/rpk-02-communication-protocol.pdf) (page 17). However, no java implementation of this protocol exists yet as far as I'm aware. While it might be a fun project for the future, I don't have time to develop it right now.

**Comment by jabrena** [comment]
Hi,

Later when I return home, I will test the example again. It is better to have more people working with the same codes. Always appear new ideas.

Cheers

Juan Antonio

**Comment by jabrena** [comment]
**Note:** Interesting project mixing robotics with Spring.

**Comment by jabrena** [comment]
Many thanks: @soblenes32 ,

I improved the performance:

``` 
ev3dev#3|21:06:48.049 [main] INFO examples.Demo8 - 168
ev3dev#3|21:06:48.077 [main] INFO examples.Demo8 - Counter: 21
ev3dev#3|21:06:48.118 [main] INFO examples.Demo8 - 166
ev3dev#3|21:06:48.147 [main] INFO examples.Demo8 - Counter: 22
ev3dev#3|21:06:48.184 [main] INFO examples.Demo8 - 77
ev3dev#3|21:06:48.208 [main] INFO examples.Demo8 - Counter: 23
ev3dev#3|21:06:48.245 [main] INFO examples.Demo8 - 90
ev3dev#3|21:06:48.258 [main] INFO examples.Demo8 - Counter: 24
ev3dev#3|21:06:48.346 [main] INFO examples.Demo8 - 166
ev3dev#3|21:06:48.376 [main] INFO examples.Demo8 - Counter: 25
ev3dev#3|21:06:48.408 [main] INFO examples.Demo8 - 122
ev3dev#3|21:06:48.433 [main] INFO examples.Demo8 - Counter: 26
ev3dev#3|21:06:48.469 [main] INFO examples.Demo8 - 167
ev3dev#3|21:06:48.500 [main] INFO examples.Demo8 - Counter: 27
ev3dev#3|21:06:48.635 [main] INFO examples.Demo8 - 332
ev3dev#3|21:06:48.671 [main] INFO examples.Demo8 - Counter: 28
ev3dev#3|21:06:48.720 [main] INFO examples.Demo8 - 166
ev3dev#3|21:06:48.781 [main] INFO examples.Demo8 - Counter: 29
ev3dev#3|21:06:48.818 [main] INFO examples.Demo8 - 167
ev3dev#3|21:06:48.912 [main] INFO examples.Demo8 - Counter: 30
ev3dev#3|21:06:48.976 [main] INFO examples.Demo8 - 167
ev3dev#3|21:06:49.028 [main] INFO examples.Demo8 - Counter: 31
ev3dev#3|21:06:49.082 [main] INFO examples.Demo8 - 167
ev3dev#3|21:06:49.138 [main] INFO examples.Demo8 - Counter: 32
ev3dev#3|21:06:49.204 [main] INFO examples.Demo8 - 165
ev3dev#3|21:06:49.248 [main] INFO examples.Demo8 - Counter: 33
ev3dev#3|21:06:49.327 [main] INFO examples.Demo8 - 168
ev3dev#3|21:06:49.345 [main] INFO examples.Demo8 - Counter: 34
ev3dev#3|21:06:49.391 [main] INFO examples.Demo8 - 166
ev3dev#3|21:06:49.414 [main] INFO examples.Demo8 - Counter: 35
ev3dev#3|21:06:49.479 [main] INFO examples.Demo8 - 167
ev3dev#3|21:06:49.502 [main] INFO examples.Demo8 - Counter: 36
ev3dev#3|21:06:49.551 [main] INFO examples.Demo8 - 133
ev3dev#3|21:06:49.567 [main] INFO examples.Demo8 - Counter: 37
ev3dev#3|21:06:49.613 [main] INFO examples.Demo8 - 69
ev3dev#3|21:06:49.634 [main] INFO examples.Demo8 - Counter: 38
ev3dev#3|21:06:49.742 [main] INFO examples.Demo8 - 95
ev3dev#3|21:06:49.779 [main] INFO examples.Demo8 - Counter: 39
ev3dev#3|21:06:49.839 [main] INFO examples.Demo8 - 168
ev3dev#3|21:06:49.888 [main] INFO examples.Demo8 - Counter: 40
ev3dev#3|21:06:49.966 [main] INFO examples.Demo8 - 166
``` 

In this example, it is possible to count that in every second, I measure:

- Second 1: 1788 samples
- Second 2: 1464 samples

Many thanks.

Cheers

**Comment by soblenes32** [comment]
@jabrena Have you noticed a blind spot between 347 degrees and 80 degrees in the lidar scan? (ie. directly opposite the cord) A lot of the scan data that I'm getting back stops abruptly at 347 or 348 and I'm not sure why yet.

**Comment by jabrena** [comment]
Hi @soblenes32, I didn´t notice, but I will check.
